### ISSUE TITLE
Automation via Oracle Jb - help on some errors

### ISSUE THREAD

**Issue by ghost** [OraOpenSource/apexbackup#8]
Hi Martin,

I have a question or two, actually some help with the APEX Backup Scrip. I have been using this script from the shell and it works perfect. However, I decided to automate many of the backup task I have by creating chains in the oracle db and adding this to schedules run by oracle.

When I got to the APEX backup script you provided i encounter a number of issue:

First I had to alter the file:$ORACLE_HOME/rdbms/admin/externaljob.ora

from:
run_user = nobody
run_group = nobody

to:
run_user = oracle
run_group = oracle

so that I would not get a permission error during the schedule run.

the second error was:

STANDARD_ERROR="/home/oracle/scripts/apexbackup/apex_backup.sh:
line 85: return: can only `return' from a function or sourced script
Exception in thread "main" java.lang.NoClassDefFoundError:
oracle/jdbc/OracleDriver"

wich I resolved by adding the following to the apex_baskup.sh file:
CLASSPATH=$CLASSPATH:/u01/app/oracle/product/11.2.0/dbhome_1/oui/jlib/classes12.jar; export CLASSPATH

I am now down to the two following errors which irequire assistance with:

STANDARD_ERROR="/home/oracle/scripts/apexbackup/apex_backup.sh:
line 85: return: can only `return' from a function or sourced script
/home/oracle/scripts/apexbackup/apex_backup.sh: line 119: sqlplus:
command not foun"

line 85 is a return call
and line 119 is the call to sqlplus to generate the report.

any sugestions?

Thank you
Daniel

**Comment by martindsouza** [comment]
@zooiduk See my response for #9
